### ISSUE TITLE
Problem in my project

### ISSUE THREAD

**Issue by Cedric-ruiu** [JCSama/CodeIgniter-develbar#1]
Hi,

In my french project with many librairies, helpers, multilangue system, etc. I immediately get an error page after install library

`Unable to load the requested language file: language/french/develbar_lang.php`

I change language to english and this time many errors appear

```
A PHP Error was encountered

Severity: Notice

Message: Undefined property: Home::$hostname

Filename: core/Model.php

Line Number: 77

Backtrace:

File: Q:\www\CodeIgniter3-cedricr\web\application_cicr\third_party\DevelBar\hooks\Develbar.php
Line: 286
Function: __get

File: Q:\www\CodeIgniter3-cedricr\web\application_cicr\third_party\DevelBar\hooks\Develbar.php
Line: 147
Function: call_user_func

File: Q:\www\CodeIgniter3-cedricr\web\index.php
Line: 292
Function: require_once
```

I can temporaly resolve with this fix in Develbar.php (line 279 & 284):

``` php
$db_server[$cobject->hostname] = $cobject->hostname;
```

to

``` php
if(isset($cobject->hostname)) $db_server[$cobject->hostname] = $cobject->hostname;
```

For the moment i have not enough time to find why errors happen but this is a first approach

**Comment by JCSama** [comment]
Hi  Cedric,
Thank you for reporting these errors :
1 - `Unable to load the requested language file: language/french/develbar_lang.php`
Because the (french) translation is missing, I added the missing file to the repository `third_party/Develbar/language/french/develbar_lang.php` you can do the same if you have other languages.

2 - `Message: Undefined property: Home::$hostname`, I don't think it has something to do with the DevelBar library, but it's most likely a typo in your model code.

**Comment by Cedric-ruiu** [comment]
1- Good! But if no language is found maybe the fallback to english language is a good way?

2- I think it comes from this base Model extended: https://github.com/jamierumbelow/codeigniter-base-model

**Comment by JCSama** [comment]
1 - Done.
2 - Fixed.
